### ISSUE TITLE
System.ArgumentException: 'End time must be after start time.'

### ISSUE THREAD

**Issue by jorgeaponte** [jchristn/GoogleMapsClient#1]
Hi @jchristn,
First of all thanks for this useful library .
I had the below error with the test project.
Maybe there is a missing commit here or in the RestWrapper project because when I point to the nuget package it works fine.

System.ArgumentException: 'End time must be after start time.'

   at Timestamps.Timestamp.set_End(Nullable`1 value)
   at RestWrapper.RestRequest.<SendInternalAsync>d__83.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at GoogleMapsClient.GoogleMaps.<GetRestResponseAsync>d__22.MoveNext() in C:\code\Github\GoogleMapsClient\src\GoogleMapsClient\GoogleMaps.cs:line 246
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at GoogleMapsClient.GoogleMaps.<GetGoogleMapsResponseAsync>d__21.MoveNext() in C:\code\Github\GoogleMapsClient\src\GoogleMapsClient\GoogleMaps.cs:line 203
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at GoogleMapsClient.GoogleMaps.<QueryAddressAsync>d__18.MoveNext() in C:\code\Github\GoogleMapsClient\src\GoogleMapsClient\GoogleMaps.cs:line 129
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Test.Program.<Main>d__4.MoveNext() in C:\code\Github\GoogleMapsClient\src\Test\Program.cs:line 76

**Comment by jchristn** [comment]
Hi @jorgeaponte thanks for your kind words.  What version are you using?  I just tested with v1.1.12 and had no issue using the ```Test``` project.

**Comment by jchristn** [comment]
Ok, yes, it looks like I need to do a dependency update and publish a new version.  Hang tight!

**Comment by jchristn** [comment]
Can you try with v1.1.13?  Just pushed to nuget.

**Comment by jorgeaponte** [comment]
It worked. Thank you very much!
I would like to create a PR to add the property PartialMatch to the GoogleMapsResponse class (to get the partial_match field), and to fix the GoogleMapsAddress.GoogleResponse value (currently it is null still when the response is OK).

**Comment by jchristn** [comment]
Sounds great!
